create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,username text unique,avatar_url text,bio text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table public.profiles enable row level security;
create policy "profiles readable" on public.profiles for select using(auth.uid() is not null);
create policy "own profile update" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),is_group boolean not null default false,title text,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.conversation_members(conversation_id uuid not null references public.conversations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,joined_at timestamptz not null default now(),primary key(conversation_id,user_id));
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,sender_id uuid not null references auth.users(id) on delete cascade,body text,kind text not null default 'text',reply_to uuid references public.messages(id) on delete set null,created_at timestamptz not null default now(),read_at timestamptz);
alter table public.conversations enable row level security;alter table public.conversation_members enable row level security;alter table public.messages enable row level security;
create policy "members read conversations" on public.conversations for select using(exists(select 1 from public.conversation_members m where m.conversation_id=id and m.user_id=auth.uid()));
create policy "members read membership" on public.conversation_members for select using(user_id=auth.uid());
create policy "members read messages" on public.messages for select using(exists(select 1 from public.conversation_members m where m.conversation_id=messages.conversation_id and m.user_id=auth.uid()));
create policy "members send messages" on public.messages for insert with check(sender_id=auth.uid() and exists(select 1 from public.conversation_members m where m.conversation_id=messages.conversation_id and m.user_id=auth.uid()));
alter table public.messages replica identity full;
do $$ begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end $$;