-- ConnectMe call signaling + call history
-- Apply this migration to the project's Supabase database.

create table if not exists public.calls (
  id uuid primary key default gen_random_uuid(),
  caller_id uuid not null references auth.users(id) on delete cascade,
  callee_id uuid not null references auth.users(id) on delete cascade,
  call_type text not null check (call_type in ('audio','video')),
  status text not null default 'ringing' check (status in ('ringing','accepted','rejected','missed','ended')),
  offer jsonb,
  answer jsonb,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice','hangup')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists calls_caller_idx on public.calls(caller_id, created_at desc);
create index if not exists calls_callee_idx on public.calls(callee_id, created_at desc);
create index if not exists call_signals_call_idx on public.call_signals(call_id, created_at);

alter table public.calls enable row level security;
alter table public.call_signals enable row level security;

drop policy if exists "calls participants can read" on public.calls;
create policy "calls participants can read"
on public.calls for select
using (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists "callers can create calls" on public.calls;
create policy "callers can create calls"
on public.calls for insert
with check (auth.uid() = caller_id);

drop policy if exists "call participants can update calls" on public.calls;
create policy "call participants can update calls"
on public.calls for update
using (auth.uid() = caller_id or auth.uid() = callee_id)
with check (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists "call participants can read signals" on public.call_signals;
create policy "call participants can read signals"
on public.call_signals for select
using (
  exists (
    select 1 from public.calls c
    where c.id = call_signals.call_id
      and (auth.uid() = c.caller_id or auth.uid() = c.callee_id)
  )
);

drop policy if exists "call participants can send signals" on public.call_signals;
create policy "call participants can send signals"
on public.call_signals for insert
with check (
  auth.uid() = sender_id
  and exists (
    select 1 from public.calls c
    where c.id = call_signals.call_id
      and (auth.uid() = c.caller_id or auth.uid() = c.callee_id)
  )
);

alter table public.calls replica identity full;
alter table public.call_signals replica identity full;

do $$ begin
  alter publication supabase_realtime add table public.calls;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.call_signals;
exception when duplicate_object then null;
end $$;

-- Safety constraints for call creation and state transitions.
alter table public.calls
  drop constraint if exists calls_not_self_check;
alter table public.calls
  add constraint calls_not_self_check check (caller_id <> callee_id);

create or replace function public.validate_call_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.caller_id <> new.caller_id or old.callee_id <> new.callee_id
     or old.call_type <> new.call_type or old.created_at <> new.created_at then
    raise exception 'immutable call fields cannot be changed';
  end if;
  if old.status in ('rejected','missed','ended') and new.status <> old.status then
    raise exception 'terminal call status cannot be reopened';
  end if;
  if old.status = 'ringing' and new.status not in ('ringing','accepted','rejected','missed','ended') then
    raise exception 'invalid call transition';
  end if;
  return new;
end;
$$;

drop trigger if exists validate_call_update on public.calls;
create trigger validate_call_update
before update on public.calls
for each row execute function public.validate_call_update();

-- Only the caller may originate offer/hangup signals; the callee may send answer/ICE.
drop policy if exists "call participants can send signals" on public.call_signals;
create policy "call participants can send signals"
on public.call_signals for insert
with check (
  auth.uid() = sender_id
  and exists (
    select 1 from public.calls c
    where c.id = call_signals.call_id
      and (
        (auth.uid() = c.caller_id and signal_type in ('offer','ice','hangup'))
        or
        (auth.uid() = c.callee_id and signal_type in ('answer','ice','hangup'))
      )
  )
);
